---
- name: Configure apt IPv4 mode
  copy:
    dest: /etc/apt/apt.conf.d/99-proxy-force-ipv4
    content: |
      Acquire::ForceIPv4 "{{ common_apt_force_ipv4 | bool | ternary('true', 'false') }}";
    owner: root
    group: root
    mode: "0644"
  when: common_apt_manage_force_ipv4 | bool

- name: Update apt cache
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Install packages
  apt:
    name:
      - curl
      - jq
      - nftables
      - wireguard
      - tcpdump
    state: present
