---
- name: Configure monitoring exporters
  hosts:
    - ru
    - non_ru
  become: true
  vars_files:
    - ../group_vars/all.yml
  pre_tasks:
    - name: Load local variable overrides
      ansible.builtin.include_vars: ../group_vars/all/local.yml
      ignore_errors: true

    - name: Load vault secrets
      ansible.builtin.include_vars: ../group_vars/all/vault.yml
      ignore_errors: true
      no_log: true

  roles:
    - monitoring_exporter
    - firewall

- name: Configure monitoring server
  hosts:
    - monitoring
    - non_ru
  become: true
  vars_files:
    - ../group_vars/all.yml
  pre_tasks:
    - name: Load local variable overrides
      ansible.builtin.include_vars: ../group_vars/all/local.yml
      ignore_errors: true

    - name: Load vault secrets
      ansible.builtin.include_vars: ../group_vars/all/vault.yml
      ignore_errors: true
      no_log: true

  roles:
    - role: monitoring_server
      when: >-
        inventory_hostname in groups.get(monitoring_server_hosts, [])
        or inventory_hostname == monitoring_server_hosts
