---
xray_install: true
xray_install_script_url: https://github.com/XTLS/Xray-install/raw/main/install-release.sh
xray_install_script_path: /tmp/xray-install-release.sh
xray_service_path: /etc/systemd/system/xray.service
xray_loglevel: warning
xray_restart_state: restarted
xray_clients_path: /usr/local/etc/xray/clients.json
xray_default_client_email: primary
xray_default_client_flow: xtls-rprx-vision
xray_sniffing_enabled: true
xray_sniffing_dest_override:
  - http
  - tls
  - quic
xray_sniffing_route_only: false
xray_client_dns_direct_enabled: true
xray_client_dns_direct_ports: "53,853"
xray_client_encrypted_dns_direct_enabled: true
xray_client_encrypted_dns_domains:
  - dns.google
  - dns64.dns.google
  - cloudflare-dns.com
  - one.one.one.one
  - security.cloudflare-dns.com
  - family.cloudflare-dns.com
  - dns.quad9.net
  - dns.adguard-dns.com
  - unfiltered.adguard-dns.com
xray_client_encrypted_dns_ips:
  - 8.8.8.8/32
  - 8.8.4.4/32
  - 1.1.1.1/32
  - 1.0.0.1/32
  - 9.9.9.9/32
  - 149.112.112.112/32
